### ISSUE TITLE
Preparing for public release

### ISSUE THREAD

**Issue by jutanke** [bonn-activity-maps/bam_annotation_tool#213]
I would like to put this repository to the dataset group on [GitHub](https://github.com/orgs/bonn-activity-maps/teams/annotation_tool). For this, we will have to make this repo __public__ so I would recommend to do this step once the first phase of the refactoring is done.

Also, the following steps have to be considered:
* choosing a proper license (atm I would go for the Apache 2.0 license)
* Creating a nice readme, with screenshots etc. (to upload images to GitHub, simply upload them to a dummy issue, then you will get a proper link that can be used in the readme.MD.

**Comment by almartmen** [comment]
Public release done.
