### ISSUE TITLE
Export: Annotations refering to image_ids which are not in the image list

### ISSUE THREAD

**Issue by dari1495** [bonn-activity-maps/bam_annotation_tool#368]
The frame ids these annotations refer to are not available in the dataset at all (there is no corresponding jpg file!). As the respective annotation has a bounding box, a track id and a person id I'm very afraid that there is a crucial bug in the backend as someone was able to annotate a frame in the tool which is not existing at all.

**Comment by anDoer** [comment]
There are still annotations which refer to non-existing image ids. 
Here is an example annotation referring to a non existing image:

`{'track_id': **105**, 
 'bbox': [976.5756718331846,
  364.7437774524158,
  138.16235504014287,
  199.23865300146412],
 'person_id': 21515,
 'id': **10171210094100**,

 'bbox_head': [],
 'scores': [],
 'category_id': 1,
 'keypoints': [],
 'image_id': **101712100941**}`

**Comment by dari1495** [comment]
It was an old file from a previous export, closing again
