### ISSUE TITLE
Duplicate Poses in the database

### ISSUE THREAD

**Issue by anDoer** [bonn-activity-maps/bam_annotation_tool#388]
Some students deleted ground truth bounding boxes for certain persons and created a new person instance to re-annotate the same person. 
What we ended up with is a ground truth person which has a head bounding box and a pose but no bounding box. 
And we have another person instance which has a bounding box, but no ground truth pose and no head bounding box. 

In order to prevent students to fix the same person twice, we need to update the database as soon as possible and remove all persons that do not have a bounding box at all. I'm a little bit afraid of a hard removal. Is there an easy way to hide such persons in the frontend?

**Comment by dari1495** [comment]
And indeed my code was wrong. I modified the script to detect persons annotated with no annotated bbox.

**Comment by dari1495** [comment]
Add a tag invalid = 1 during export to those persons with no bbox annotated
