### ISSUE TITLE
PT Export: Fix negative numbers issue

### ISSUE THREAD

**Issue by dari1495** [bonn-activity-maps/bam_annotation_tool#430]
Make negative numbers 0

**Comment by anDoer** [comment]
Please clamp all coordinates outside of the frame, i.e. set 
```
x = max(min(width - 1, x), 0)
y = max(min(height - 1, y), 0)
```

**Comment by anDoer** [comment]
We have a special case with head bounding boxes: 
as head bounding boxes are only required for evaluation (the length of the head bounding boxe's diagonal determines the person height), clamping negative coordinates would be harmful. 

For that reason we should allow negative numbers for head bounding boxes. 
**This makes it necessary to change to export format of head bounding boxes from**

`[x1, y1, width, height]` **to** `[x1, y1, x2, y2]`
