### ISSUE TITLE
Export: Bad Head BBox Format

### ISSUE THREAD

**Issue by anDoer** [bonn-activity-maps/bam_annotation_tool#450]
In the current export, head bboxes have the following format
`[[x1, y1], [x2, y2]]` 
and consecuently, an empty head bbox is simply
`[[], []]
`

Head Bounding boxes should be exported as follows 
`[x1, y1, x2, y2]`

**Comment by dari1495** [comment]
Sequence 014235
Track ID 0, Person ID 30934
Image 37
