### ISSUE TITLE
Drawing non-interactive object keypoints as guiding help for annotation

### ISSUE THREAD

**Issue by dari1495** [bonn-activity-maps/bam_annotation_tool#456]
After finishing the sanity check in #399 the annotators will have to fix the issues it detects. This is inconvenient for cases where there are:
- Person keypoints outside of bounding box
- bbox_head outside of bounding box
A way to help the annotators be quicker and more precise would be to be able to **visualize the bounding box and the editable object at the same time** 

Other bonus ideas:
- Click on the sanity check issue to automatically select the affected object.

**Comment by dari1495** [comment]
We can just draw a rectangle in the bbox position, no need to make it switchable or editable.

**Comment by almartmen** [comment]
Implemented. There is an option in the options panel that can be also toggled by using the shortcut "Shift + B".
If no object is selected, every Bounding Box is drawn. If an object is selected only its Bounding Box is drawn.
